# Generated by Django 6.1.1 on 2026-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='area',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='description',
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='petition_photo',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
